language: ruby
rvm:
  - 1.8.7
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=2.7.19
  - PUPPET_VERSION=3.0.1 # Breaks due to rodjek/rspec-puppet#58
notifications:
  email: false
gemfile: .gemfile
