name 'purplehazech-apache'
version '0.5.0'

author ''
license 'Apache 2.0'
project_page 'https://github.com/purplehazech/puppetlabs-apache'
source 'git://github.com/purplehazech/puppetlabs-apache.git'
summary 'Puppet module for Apache'
description 'Module for Apache configuration'
dependency 'puppetlabs/firewall', '>=0.0.4'
dependency 'puppetlabs/stdlib', '>=2.2.1'
